name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message:
          'Thanks for creating an issue! I try to respond as quickly as possible
          to all issues. If it has been a while feel free to mention me to get
          my attention.'
        pr-message: 'Thanks for the PR! I should review it shortly!'
